### ISSUE TITLE
Dynamic Recursive Box Creation with Accessibility and Improved UI in hacked fun 

### ISSUE THREAD

**Issue by Jitmisra** [hariom1616/Tech-Inventory#10]
This code creates an interactive box that, when clicked, recursively spawns smaller boxes inside it. Each box dynamically updates its content with a counter showing how many boxes have been opened. The design improves accessibility by adding ARIA attributes and ensures a smooth, user-friendly experience with proper visual feedback and transitions. The CSS has been optimized for easy customization with variables for colors, and the JavaScript logic has been refined for better performance and clarity.

**Comment by Jitmisra** [comment]
please assigned this issue to me

**Comment by hariom1616** [comment]
Do the Needful..

**Comment by Jitmisra** [comment]
merged thanks
