### ISSUE TITLE
Title and Meta Description Enhancement

### ISSUE THREAD

**Issue by Jitmisra** [hariom1616/Tech-Inventory#12]
1.	SEO Optimization:
	•	Title: Changed to “Funny Joke Generator - Laugh Now!” for clarity.
	•	Meta Description: Added a description for better SEO.
	2.	Enhanced Button Animation: Button now has a smoother animation when hovered.
	3.	Message Fade-In: The joke now fades in smoothly when displayed.
	4.	Color Transition: Smoother color transitions for background changes.

**Comment by Jitmisra** [comment]
please assign this issue to me

**Comment by hariom1616** [comment]
do the needful changes.
