### ISSUE TITLE
Enhancing Visual Appeal and User Experience in Flower Animation Webpage

### ISSUE THREAD

**Issue by Jitmisra** [hariom1616/Tech-Inventory#8]
Title & Description: The title now reflects the relaxing nature of the animation, while the meta description provides a clear summary of the page.
	2.	Gradient Background: Added a gradient background to make the scene softer and more visually appealing.
	3.	Rotation Animation: The flowers now rotate as they fall, giving the animation a more dynamic and natural feel.
	4.	Pointer Events Disabled: Flowers won’t interfere with any interaction on the page, making the effect purely decorative.
	5.	Slightly Slower Interval: Increased the interval between flower generation for a calmer, more soothing pace.

**Comment by Jitmisra** [comment]
please assign this issue to me for hacktoberfest 2024

**Comment by hariom1616** [comment]
please do the needful.

**Comment by Jitmisra** [comment]
yea merged thanks
